### PR TITLE
Dig rate limiter

### PR DESCRIPTION
**Pull request by S-S-X**
https://github.com/pandorabox-io/pandorabox.io/issues/611

+ some general client side cheat mitigation.

By default digging rate is not limited.

### CODE REVIEW

**Comment by S-S-X** [comment]
Should configuration value be XP / second instead of direct rate limiter parameter?
I think that would probably be better.

**Comment by S-S-X** [comment]
Well, not easy enough for me to add XP / second so it is XP additions / second. And now line too long for luacheck..

**Comment by S-S-X** [comment]
pls squash if merging this pile

**Comment by BuckarooBanzay** [comment]
nice work :+1:
any recommendations for the `xp.limit_dig_rate` setting? i'm thinking 2 or 3 should be a sane value, we might even have to adjust the xp-priv thresholds afterwards to keep is somewhat fair...

**Comment by S-S-X** [comment]
> any recommendations for the `xp.limit_dig_rate` setting? i'm thinking 2 or 3 should be a sane value, we might even have to adjust the xp-priv thresholds afterwards to keep is somewhat fair...

I think higher values would be okay to keep some variation, for sure setting to 2-3 would reduce sand digging as it would be about same XP no matter what you'd be digging. Sand digging can easily give 16 XP / second with high level tools.

Added bamboo and papyrus dig limits are not that easy to predict as I think recursion was limited based on player position, not digged node position.

I think something between 15 - 20 could work well enough, I would rather keep limit high at first and maybe bring it down if it seems that it would be somehow useful.

**Comment by OgelGames** [comment]
Yeah, I think it would be unfair to limit it too much, especially with the fast digging tools we have. From my testing, the fastest one can dig stone is about 19 nodes/second (max level lava multitool), and the fastest for sand is about 27 n/s. 

So I think a limit of 20 is probably about right, as it limits XP from sand digging and other fast-digging nodes, but not regular mining.

**Comment by BuckarooBanzay** [comment]
done :+1: https://github.com/pandorabox-io/pandorabox.io/commit/c2ac04e281053240082c4d5c3005f7309eaeed42

**Comment by SwissalpS** [comment]
as long as my tool still digs at it's level :)

**Pull request merged**
